### PR TITLE
Links patch

### PR DESCRIPTION
**Pull request by AhmedHalat**

### CODE REVIEW

**Comment by AhmedHalat** [comment]
Patched missing download links

**Comment by BishopOfTurkey** [comment]
You should probably remove some of the changes which introduce dependencies on your github page.

**Comment by AhmedHalat** [comment]
Sorry about that, I didn't mean to create a pull request with your repo. I figured this repo was inactive.

Should I edit my changes and have you review, or simply close this thread?

**Comment by BishopOfTurkey** [comment]
Not actually my repo, but it looks like the owner is still active.

**Pull request closed without merging**
